name: wch gcc compile

on:
  workflow_dispatch:

run-name: ${{ github.actor }} 🚀

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get GCC
      run: wget https://github.com/fiskov/compilers/releases/download/0.0.1/RISC-V_Embedded_GCC12.tar.xz -nv

    - name: Unpack GCC
      run: |
        tar xf RISC-V_Embedded_GCC12.tar.xz
        echo "GCC_PATH=$PWD/RISC-V_Embedded_GCC12/bin" >> "$GITHUB_ENV"

    - name: Build
      run: |
        make GCC_TOOLCHAIN=$GCC_PATH
        echo "FW_MCU_NAME=fw_$(cat version)" >> "$GITHUB_ENV"
        tar --transform 's,.*/,,g' -cvzf $FW_MCU_NAME.tar.gz version _build/app.bin

    - name: Update Nightly Release
      uses: andelf/nightly-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly
        name: "nightly release $$"
        draft: false
        prerelease: true
        body: |
          This is a nightly binary release
        files: |
          $FW_MCU_NAME.tar.gz
