name: wch gcc compile

on:
  workflow_dispatch:

run-name: ${{ github.actor }} 🚀

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get GCC
      run: wget https://github.com/fiskov/compilers/releases/download/0.0.1/RISC-V_Embedded_GCC12.tar.xz -nv

    - name: Unpack GCC
      run: |
        tar xf RISC-V_Embedded_GCC12.tar.xz

    - name: Build
      run: |
        make GCC_TOOLCHAIN=$PWD/RISC-V_Embedded_GCC12/bin

    - name: version
      run: |
        echo "VERSION=$(cat version)" >> "$GITHUB_ENV"
        tar --transform 's,.*/,,g' -cvzf fw_$VERSION.tar.gz version _build/app.bin
        ls -ahl

    - name: release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        draft: false
        prerelease: false
        release_name: firmware v${{ env.VERSION }}
        tag_name: v${{ env.VERSION }}
        body_path: CHANGELOG.md

    - name: upload artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: fw_${{ env.VERSION }}.tar.gz
        asset_name: fw_${{ env.VERSION }}.tar.gz
        asset_content_type: application/gzip
